In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

In [2]:
def create_dataset(n_rows=1000):
    discounts = [0, 0.05, 0.1, 0.25, 0.50]
    
    data = {
        'product_id': np.arange(1, n_rows+1),
        'quantity': np.random.randint(1, 100, size=n_rows),
        'price': np.round(np.random.uniform(10.0, 500.0, size=n_rows), 2),
        'discount': np.random.choice(discounts, size=n_rows)
    }
    
    df = pd.DataFrame(data=data)
    df['total'] = np.round(df['quantity'] * df['price'] * (1 - df['discount']), 2)
    
    error_indexes = np.random.choice(df.index, size=int(n_rows * 0.1), replace=False)
    df.loc[error_indexes, 'total'] = df.loc[error_indexes, 'total'] * np.random.uniform(1.1, 1.5, size=len(error_indexes))
    
    print(f'Generated {n_rows} rows. Errors: {len(error_indexes)}')
    
    return df

In [3]:
df = create_dataset()

Generated 1000 rows. Errors: 100

In [4]:
df.head(10)

   product_id  quantity   price  discount     total
0           1        52  307.70      0.05  15200.38
1           2        93  129.73      0.25   9048.67
2           3        15  254.14      0.05   3621.50
3           4        72  171.87      0.10  11137.18
4           5        61  467.51      0.10  25666.30
5           6        21   13.69      0.25    215.62
6           7        83  120.41      0.50   4997.01
7           8        87  189.02      0.25  12333.56
8           9        75  249.03      0.05  17743.39
9          10        75  426.90      0.25  24013.12

In [5]:
df['correct_total'] = np.round(df['quantity'] * df['price'] * (1 - df['discount']), 2)

mismatches = df[np.abs(df['total'] - df['correct_total']) > 0.01]

mae = np.abs(df['total'] - df['correct_total']).mean()

print(f'Знайдено невідповідностей: {len(mismatches)}')
print(f'Середня абсолютна різниця (MAE): {mae:.2f}')

Знайдено невідповідностей: 100
Середня абсолютна різниця (MAE): 293.84

In [8]:
df.loc[df['total'] != df['correct_total']]

     product_id  quantity   price  discount         total  correct_total
10           11        88   53.06      0.00   6254.678740        4669.28
17           18        30  498.66      0.25  12989.838030       11219.85
20           21        64  459.52      0.10  33976.777542       26468.35
36           37        62  356.54      0.50  15983.116847       11052.74
41           42        55  167.11      0.00  13085.571404        9191.05
..          ...       ...     ...       ...           ...            ...
967         968        18  379.87      0.50   4966.414658        3418.83
978         979        86  487.34      0.50  29642.627535       20955.62
979         980        90   19.81      0.10   2295.547422        1604.61
996         997        41  179.70      0.05   8859.784233        6999.32
999        1000        26  414.39      0.05  11374.884227       10235.43

[100 rows x 6 columns]